apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-production-e2e-deployment
spec:
  selector:
    matchLabels:
      app: complete-production-e2e-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: complete-production-e2e-deployment
    spec:
      containers:
      - name: complete-production-e2e-deployment
        image: kofipat/complete-prodcution-e2e-pipeline:CHANGEME
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
